import { useRouter } from "next/router"
import Layout from "../../components/Layout"

export default function ProfilePage() {

    const router = useRouter()
    const { username } = router.query

    return (
        <>
            <Layout title="Profile Page">
                <div>Hello {username}</div>
                <p>This page is generated by /profile/[username] using next/router.</p>
            </Layout>
        </>
    )
}